blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Create Custom Symbols Official Website
    url: https://wangchujiang.com/create-custom-symbols/
    about: Introduction to the Create Custom Symbols app on the official website!